#
# Installs Tomcat, following best practices of separating CATALINA_BASE directory from CATALINA_HOME
#
---
- name: Tomcat | Install Tomcat
  include: install-tomcat.yml

- name: Tomcat | configure-setenv.yml
  include: configure-tomcat.yml

- name: Tomcat | restart tomcat
  include: restart-tomcat.yml
